services:
  warehouse_postgres:
    image: postgres:latest
    container_name: warehouse_postgres
    command: -p ${POSTGRES_PORT:?err}
    expose:
      - ${POSTGRES_PORT:?err}
    ports:
      - ${POSTGRES_PORT:?err}:${POSTGRES_PORT:?err}
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DATABASE:?err}
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
  warehouse_app:
    container_name: warehouse_app
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - warehouse_postgres
volumes:
  postgres_data: